### ISSUE TITLE
What use is this?

### ISSUE THREAD

**Issue by Sod-Almighty** [elliotwoods/msgpack-arduino#2]
If I don't want to pack data into a stream - e.g. `Serial` - then this library is pretty much useless. How the hell do I pack into a string? Every class constructor takes a `Stream&` - where am I getting this stream from?

It would be easier to write my own implementation than try to force yours to work.

**Comment by elliotwoods** [comment]
Arduino doesn't have `string` like in C++, but it does have `String` , which can be used as a `Stream` (e.g. via https://gist.github.com/arcao/3252bb6e5e52493f03726ec32e61395c )

However, what is your use case?
In my experience I'd very quickly run out of memory if I wanted to serialise something to memory on the arduino. And therefore serialising something directly to the target (e.g. a serial port, an SD card, etc), seems much more logical than serialising to a string first and then sending that.

The nature of open source is that you are entirely welcome to write your own, and take code from mine to help in doing so. This code is distributed under MIT license. I'll make that more explicit.
